"use client";

import { useEffect, useState } from "react";
import Script from "next/script";

const AutoTranslator = () => {
    const [isMounted, setIsMounted] = useState(false);

    useEffect(() => {
        setIsMounted(true);
    }, []);

    useEffect(() => {
        if (!isMounted) return;

        // Define the callback for Google Translate
        (window as any).googleTranslateElementInit = () => {
            new (window as any).google.translate.TranslateElement(
                {
                    pageLanguage: "en",
                    // Including common languages for the UNIBEN/African context and global reach
                    includedLanguages: "en,fr,es,de,pt,ar,zh-CN,hi,yo,ig,ha",
                    autoDisplay: false,
                },
                "google_translate_element"
            );
        };

        const detectAndTranslate = async () => {
            try {
                const userLang = (navigator.language || (navigator as any).userLanguage).split('-')[0].toLowerCase();

                // Supported languages excluding English
                const supportedLanguages = ["fr", "es", "de", "pt", "ar", "zh", "hi", "yo", "ig", "ha"];

                if (supportedLanguages.includes(userLang) || (userLang === "zh-cn" || userLang === "zh")) {
                    const targetLang = userLang.startsWith("zh") ? "zh-CN" : userLang;

                    const checkTranslate = setInterval(() => {
                        const selectField = document.querySelector(".goog-te-combo") as HTMLSelectElement;
                        if (selectField) {
                            clearInterval(checkTranslate);
                            if (selectField.value !== targetLang) {
                                selectField.value = targetLang;
                                selectField.dispatchEvent(new Event("change"));
                            }
                        }
                    }, 500);

                    // Timeout after 10 seconds to stop checking
                    setTimeout(() => clearInterval(checkTranslate), 10000);
                }
            } catch (err) {
                console.error("Translation detection error:", err);
            }
        };

        detectAndTranslate();
    }, [isMounted]);

    if (!isMounted) return null;

    return (
        <>
            <Script
                id="google-translate-script"
                src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
                strategy="afterInteractive"
            />
            <style
                dangerouslySetInnerHTML={{
                    __html: `
        /* Hide unwanted Google Translate UI elements */
        iframe.goog-te-banner-frame,
        #goog-gt-tt,
        .goog-te-balloon-frame,
        .goog-te-banner-frame.skiptranslate {
          display: none !important;
          visibility: hidden !important;
          opacity: 0 !important;
        }

        body {
          top: 0 !important;
          position: relative !important;
        }

        /* Prevent shifting */
        body {
            top: 0px !important; 
        }

        /* Style the dropdown to match the site's aesthetic */
        .google-translate-container {
            display: inline-block;
        }

        /* The actual select element generated by Google */
        .goog-te-combo {
            padding: 8px 12px !important;
            border-radius: 10px !important;
            background-color: transparent !important;
            border: 1px solid #e5e7eb !important; /* light gray border */
            color: #4b5563 !important; /* text gray */
            font-size: 12px !important;
            font-weight: 600 !important;
            text-transform: uppercase !important;
            letter-spacing: 0.05em !important;
            outline: none !important;
            transition: all 0.2s ease !important;
            cursor: pointer !important;
        }

        .dark .goog-te-combo {
            background-color: #030712 !important; /* gray-950 */
            border-color: #111827 !important; /* gray-900 or similar */
            color: #9ca3af !important; /* gray-400 */
        }

        .goog-te-combo:hover {
            border-color: #2563eb !important; /* blue-600 */
        }

        /* Hide the "Powered by Google Translate" branding if desired for a cleaner look */
        .goog-logo-link, .goog-te-gadget span {
            display: none !important;
        }
        
        .goog-te-gadget {
            font-size: 0 !important;
            color: transparent !important;
        }
      `,
                }}
            />
        </>
    );
};

export default AutoTranslator;
